-- PostgreSQL compatibiliteit
SET DATABASE TRANSACTION CONTROL MVCC;
SET DATABASE SQL SYNTAX PGS TRUE;

DROP SCHEMA IF EXISTS pagila CASCADE;
CREATE SCHEMA pagila;

-- alternative for mpaa_rating enum (enums are not possible in hsqldb)
CREATE TABLE pagila.mpaa_rating (
  rating VARCHAR(8) NOT NULL
);
INSERT INTO pagila.mpaa_rating (rating) VALUES ('G',
                                                'PG',
                                                'PG-13',
                                                'R',
                                                'NC-17');
ALTER TABLE pagila.mpaa_rating
  ADD UNIQUE (rating);

-- NB: niet optimaal -> omwegen nodig voor enum, tsvector, array
CREATE SEQUENCE pagila.film_film_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;
CREATE TABLE pagila.film (
  film_id          INTEGER GENERATED BY DEFAULT AS SEQUENCE film_film_id_seq NOT NULL,
  title            CHARACTER VARYING(255)                                    NOT NULL,
  description      VARCHAR(250),
  release_year     INTEGER,
  language_id      SMALLINT                                                  NOT NULL,
  rental_duration  SMALLINT DEFAULT 3                                        NOT NULL,
  rental_rate      NUMERIC(4, 2) DEFAULT 4.99                                NOT NULL,
  length           SMALLINT,
  replacement_cost NUMERIC(5, 2) DEFAULT 19.99                               NOT NULL,
  rating           VARCHAR(8) DEFAULT 'G',
  FOREIGN KEY (rating) REFERENCES mpaa_rating (rating),
  last_update      TIMESTAMP WITHOUT TIME ZONE DEFAULT now()                 NOT NULL
  ,
  special_features VARCHAR(250) ARRAY [10]
  -- fulltext tsvector NOT NULL
);


INSERT INTO pagila.film (film_id, title, description, release_year, language_id, rental_duration, rental_rate, length, replacement_cost, rating, last_update, special_features)
VALUES
  (1, 'Chamber Italian', 'A Fateful Reflection of a Moose And a Husband who must Overcome a Monkey in Nigeria', 2006, 1,
      7, 4.99, 117, 14.99, 'NC-17', '2013-05-26 14:50:58.951', ARRAY ['Features']);
